# Joker Theme Configuration (Enhanced)

# ----------------------------------------------------- 
# Wallpapers
# ----------------------------------------------------- 
# exec = swaybg -m fill -i $HOME/.config/hypr/themes/Joker/wallpapers/18.jpg

# ----------------------------------------------------- 
# Gtk Stuff
# ----------------------------------------------------- 
$GTK_THEME = Joker
$ICON_THEME = Joker-Icons
$COLOR_SCHEME = prefer-dark

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

# ----------------------------------------------------- 
# General
# ----------------------------------------------------- 
general {
    gaps_in = 6
    gaps_out = 12
    border_size = 3
    # گرادینت قرمز-مشکی برای پنجره فعال
    col.active_border = rgba(ff003cff) rgba(100c14ff) 45deg
    col.inactive_border = rgba(100c14aa)
    layout = dwindle
    resize_on_border = true
}

# ----------------------------------------------------- 
# Decoration
# ----------------------------------------------------- 
decoration {
    rounding = 15
    shadow_range = 10
    shadow_render_power = 3
    col.shadow = rgba(000000ee)

    blur {
        enabled = yes
        size = 8
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

# ----------------------------------------------------- 
# Group
# ----------------------------------------------------- 
group {
    col.border_active = rgba(ff003cff) rgba(100c14ff) 45deg
    col.border_inactive = rgba(100c14aa)
    col.border_locked_active = rgba(ff003cff) rgba(100c14ff) 45deg
    col.border_locked_inactive = rgba(100c14aa)
}

# ----------------------------------------------------- 
# Layer Rules
# ----------------------------------------------------- 
layerrule = unset,waybar